[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shared-string = "0.1.7"
serde = "1.0.150"
serde_derive = "1.0.150"
thiserror = "1.0.37"
axum = "0.6.1"

